name: Deploy the lambda using AWS SAM
on:
  push:
    branches:
      - main
      - refactor-app-include-pulumi
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: protected
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to AWS Lambda
        env:
          AWS_ARN_ROLE: ${{ secrets.AWS_ARN_ROLE }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.REPO }}
          WORKFLOW_FILE_NAME: ${{ secrets.WORKFLOW_FILE_NAME }}
          BRANCH: ${{ secrets.BRANCH }}
          JOB_FILTER: ${{ secrets.JOB_FILTER }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          FULL_DOMAIN_NAME: ${{ secrets.FULL_DOMAIN_NAME }}
          TLS_CERTIFICATE_ARN: ${{ secrets.TLS_CERTIFICATE_ARN }}
        run: make up