name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy-gcf
    runs-on: ubuntu-latest
    environment: protected
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          # probot/example-google-cloud-function credentials provided by @bcoe
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Deploy to GCF
        run: |
          gcloud beta functions deploy ghrunner-app-function \
            --runtime nodejs16 \
            --allow-unauthenticated \
            --trigger-http \
            --entry-point probotApp \
            --service-account=${{ secrets.SERVICE_ACCOUNT }} \
            --set-secrets 'APP_ID=APP_ID:latest,PRIVATE_KEY=PRIVATE_KEY:latest,WEBHOOK_SECRET=WEBHOOK_SECRET:latest'`
