name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy-gcf
    runs-on: ubuntu-latest
    environment: protected
    steps:
      - uses: actions/checkout@v2
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - name: Deploy to GCF
        env:
          OWNER: pavlovic-ivan
          REPO: ILGPU
          WORKFLOW_FILE_NAME: runners.yaml
          BRANCH: master
          JOB_FILTER: cuda
        run: make deploy project=${{ secrets.PROJECT_ID }} service_account=${{ secrets.SERVICE_ACCOUNT }}