name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy-gcf
    runs-on: ubuntu-latest
    environment: protected
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - name: Deploy to GCF
        run: make deploy project=${{ secrets.PROJECT_ID }} service_account=${{ secrets.SERVICE_ACCOUNT }}