name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy-gcf
    runs-on: ubuntu-latest
    environment: protected
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
      - name: Deploy to GCF
        run: |
          gcloud beta functions deploy ghrunner-app-function \
            --runtime nodejs16 \
            --allow-unauthenticated \
            --trigger-http \
            --entry-point probotApp \
            --service-account=${{ secrets.SERVICE_ACCOUNT }} \
            --set-secrets 'APP_ID=APP_ID:latest,PRIVATE_KEY=PRIVATE_KEY:latest,WEBHOOK_SECRET=WEBHOOK_SECRET:latest'`
